### ISSUE TITLE
Requires mechanism to disable or modify character key shortcuts

### ISSUE THREAD

**Issue by waako** [markconroy/localgov_keynav#1]
As these keyboard shortcuts only use letter characters, a mechanism to turn off or remap the trigger shortcut.

See WCAG 2.1.4 Character Key Shorts (A): https://www.w3.org/WAI/WCAG21/Understanding/character-key-shortcuts.html

**Comment by markconroy** [comment]
Fixed by: https://github.com/markconroy/localgov_keynav/commit/3d6c4504bd8f2a9156fbbe8c958dc4354239b0db
